<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationInsightsResourceId>/subscriptions/0297c458-3533-4931-b055-532cea99eb4b/resourcegroups/Lab1/providers/microsoft.insights/components/WebAppLab1</ApplicationInsightsResourceId>
    <UserSecretsId>2feea2b7-d7cc-4742-835b-f480261b5ce7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.17.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
  </ItemGroup>

</Project>
